# Generated by Django 2.0.6 on 2018-06-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alan1', models.CharField(blank=True, max_length=20, null=True)),
                ('alan2', models.CharField(blank=True, max_length=20, null=True)),
                ('alan3', models.CharField(blank=True, max_length=20, null=True)),
                ('alan4', models.CharField(blank=True, max_length=20, null=True)),
                ('alan5', models.CharField(blank=True, max_length=20, null=True)),
                ('alan6', models.CharField(blank=True, max_length=20, null=True)),
                ('alan7', models.CharField(blank=True, max_length=20, null=True)),
                ('alan8', models.CharField(blank=True, max_length=20, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='device.Device')),
            ],
        ),
    ]
